### PR TITLE
Add support for podman

### LINKED ISSUE #1: Podman?
Given that Podman is *the* supported container technology on RH based distros, any chance of supporting that with this package?

### PR DESCRIPTION
**Pull request by goncalossilva**
Closes #1 

@brianjmurrell I don't have an easy way to test this on a RH system, but this should do it.

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Any chance you can land this and do a new build in COPR with it?

**Comment by goncalossilva** [comment]
Give it a try please?

**Comment by brianjmurrell** [comment]
Doesn't seem to be quite right yet I don't think.  I have your previous `0.2.64-1.fc40` installed but I forced installation of `podman-docker` with it using `rpm … --nodeps`.  So currently installed, I have:

```
$ rpm -qa | grep -e podman -e docker -e moby
docker-rhel-push-plugin-1.13.1-68.git47e2230.fc30.x86_64
podman-plugins-4.9.4-1.fc39.x86_64
podman-5.1.1-1.fc40.x86_64
podman-remote-5.1.1-1.fc40.x86_64
podman-docker-5.1.1-1.fc40.noarch
```

Trying to install your new `0.2.64-1.fc40`:

```
$ sudo dnf reinstall act-cli --best --allowerasing
test                                            2.8 MB/s | 2.9 kB     00:00    
Dependencies resolved.
================================================================================
 Package       Arch   Version        Repository                            Size
================================================================================
Reinstalling:
 act-cli       x86_64 0.2.64-1.fc40  copr:copr.fedorainfracloud.org:goncalossilva:act
                                                                          5.8 M
Installing dependencies:
 moby-engine   x86_64 24.0.5-4.fc40  fedora                                28 M
Removing dependent packages:
 podman-docker noarch 5:5.1.1-1.fc40 @@System                              11 k

Transaction Summary
================================================================================
Install  1 Package
Remove   1 Package

Total download size: 34 M
Is this ok [y/N]: 
```

Clearly that's not what I want to do.

Inspecting the repo a bit:

```
$ sudo dnf repoquery --qf ${name}-%{evr}\ %{repoid} --requires act-cli
test                                                                                                                                                                                                        2.8 MB/s | 2.9 kB     00:00    
(moby or docker or docker-ce or docker-ce-cli or docker-ee)
(moby or podman or docker or docker-ce or docker-ce-cli or docker-ee)
/bin/sh
git
golang
libc.so.6(GLIBC_2.34)(64bit)
rtld(GNU_HASH)
```

The first two lines are the most interesting as they seem to reflect the old and new builds of `0.2.64-1.fc40`.  I can't help but wonder if both the old and new builds of `0.2.64-1.fc40` are being referred to there.

Maybe it would help clarify things if you bumped the `Release:` to `2` so that it very clearly supersedes the `-1` one.

**Comment by goncalossilva** [comment]
That is indeed interesting. I'm not exactly sure how `dnf` caching may be influencing what you're seeing. `dnf clean` might have have helped. Regardless, I agree that bumping the release is the right thing to do here. I'll tackle that in a few hours.

**Comment by goncalossilva** [comment]
Building and should be live in a minute or two, please give it a try.

FWIW I think `act` is publishing a new release tomorrow so we'll discard the old config one way or another.

Thanks for the feedback and help so far!

**Comment by brianjmurrell** [comment]
I was able to `sudo dnf upgrade act-cli` to get upgraded to `act-cli-0.2.65-1.fc40.x86_64`.

I'm surprised that my daily _dnf-automatic_ didn't upgrade it automatically but the package itself seems to upgrade so this seems resolved:

```
$ rpm -qa | grep -e podman -e docker -e moby
docker-rhel-push-plugin-1.13.1-68.git47e2230.fc30.x86_64
podman-plugins-4.9.4-1.fc39.x86_64
podman-5.1.2-1.fc40.x86_64
podman-docker-5.1.2-1.fc40.noarch
podman-remote-5.1.2-1.fc40.x86_64
```

**Pull request merged**
